import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Smartphone,Sparkles,ArrowRight,CheckCircle2,Download,Loader2,AlertCircle} from "lucide-react";
import "./styles.css";

function App(){
 const [url,setUrl]=useState(""),[appName,setAppName]=useState("My Web App"),[packageId,setPackageId]=useState("com.web2apk.app"),[job,setJob]=useState(null),[error,setError]=useState("");
 useEffect(()=>{if(!job?.jobId||["completed","failed"].includes(job.status))return;const t=setInterval(async()=>{try{const r=await fetch("/api/build/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.jobId})});const d=await r.json();if(r.ok)setJob(x=>({...x,...d}));}catch{}},3000);return()=>clearInterval(t)},[job?.jobId,job?.status]);
 const build=async()=>{setError("");setJob(null);try{const r=await fetch("/api/build/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,appName,packageId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not start build.");setJob(d);}catch(e){setError(e.message)}};
 return <div className="app"><main><section className="hero"><div className="pill"><Sparkles size={15}/> AI-powered APK builder</div><h1>Turn your web app into an<br/><em>Android APK.</em></h1><p>Enter your live website URL. Web2APK builds APK/AAB on a dedicated Android server — no GitHub Actions required.</p></section><section className="card"><div className="iconbox"><Smartphone/></div><h2>Build your Android app</h2><label>Web app URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-app.vercel.app"/><label>App name</label><input value={appName} onChange={e=>setAppName(e.target.value)} maxLength={50}/><label>Package ID</label><input value={packageId} onChange={e=>setPackageId(e.target.value.toLowerCase().replace(/[^a-z0-9.]/g,""))}/>{error&&<div className="error"><AlertCircle size={17}/>{error}</div>}{!job&&<button className="primary" onClick={build} disabled={!url||!appName||!packageId}>Build APK <ArrowRight size={18}/></button>}{job&&<div className="buildstatus">{job.status==="completed"?<CheckCircle2 size={30}/>:job.status==="failed"?<AlertCircle size={30}/>:<Loader2 className="spin" size={30}/>}<div><b>{job.message||job.status}</b><small>{job.status}</small></div>{job.status==="completed"&&<div className="downloads"><a className="primary download-link" href={"/api/build/download?jobId="+job.jobId+"&type=apk"}><Download size={18}/> Download APK</a><a className="secondary-link" href={"/api/build/download?jobId="+job.jobId+"&type=aab"}>Download AAB</a></div>}{job.status==="failed"&&<button className="primary" onClick={()=>setJob(null)}>Try Again</button>}</div>}</section></main><footer>Web2APK AI · Website → Capacitor → Android APK/AAB</footer></div>;
}
createRoot(document.getElementById("root")).render(<App />);
